/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vindecoder;

import java.util.HashMap;

/**
 *
 * @author Rosario Marin
 */
class CatalogueManufacturer extends HashMap<String, String> {

  private static final String ManufacturerCodes[] = {
      "AL", "British Leyland Rover Group",
      "AU", "Motor Coach Industries Classic",
      "BA", "Blue Bird bus",
      "BB", "Blue Bird multi-purpose vehicle",
      "BC", "Blue Bird truck",
      "BD", "Blue Bird incomplete vehicle",
      "BE", "Blue Bird",
      "BF", "Blue Bird",
      "BG", "Blue Bird",
      "B1", "Ontario Bus Industries / Orion Bus Industries",
      "DF", "Ferrari SpA Dino",
      "E2", "Van Hool NV",
      "FB", "Ford Motor Company bus (E350/E550)",
      "FC", "Ford Motor Company stripped chassis",
      "FD", "Ford Motor Company incomplete vehicle (cutaway cab)",
      "FE", "Ford Motor Company incomplete vehicle (cutaway cab)",
      "FF", "Ford Motor Company \"glider\" kit (no engine or powertrain)",
      "FF", "Ferrari SpA",
      "FM", "Ford Motor Company multi-purpose vehicle (Explorer)",
      "FT", "Ford Motor Company truck",
      "FY", "Flyer Industries Ltd./New Flyer Industries",
      "GA", "Chevrolet van",
      "GB", "Chevrolet van chasis",
      "GC", "Chevrolet pickup",
      "GD", "General Motors Corporation van chasis",
      "GH", "General Motors Corp. Diesel Division",
      "GJ", "General Motors Corporation van",
      "GN", "Chevrolet Astro/Blazer/Suburban",
      "GT", "General Motors Corp. Sierra pickup",
      "G0", "General Motors Corp. Truck & Coach",
      "G5", "General Motors Corp. Jimmy/Suburban",
      "G9", "Motor Coach Industries Classic",
      "MH", "Mercury incomplete vehicle",
      "M2", "Mercury multi-purpose vehicle",
      "M3", "Mercury incomplete vehicle",
      "M4", "Mercury truck",
      "M8", "Motor Coach Industries highway coaches",
      "NV", "Nova Bus Corporation",
      "N9", "Neoplan USA Corporation North American Bus Industries",
      "PC", "Prevost Car Compagnie",
      "P9", "Prevost Car Compagnie",
      "RK", "Nova Bus Corporation",
      "TU", "Transportation Manufacturing Corporation",
      "V1", "AB Volvo",
      "VH", "Bus Industries of America",
      "G1", "Chevrolet",
      "L1", "Chevrolet",
      "G2", "Pontiac",
      "Y2", "Pontiac",
      "G2", "Pontiac",
      "L2", "Pontiac",
      "G3", "Oldsmobile",
      "G4", "Buick",
      "G6", "Cadillac",
      "G8", "Saturn",
      "BG", "Chevrolet",
      "AG", "Chevrolet",
      "GG", "Chevrolet",
      "AV", "Volkswagen",/* updated */
      "HT", "Toyota",
      "FA", "Ford",
      "L9", "Wallyscar",
      "JA", "Isuzu",
      "C1", "Fiat Automobiles/Mazda",
      "JF", "Fuji Heavy Industries",
      "HL", "Honda",
      "HM", "Honda",
      "MB", "Mitsubishi",
      "M6", "Mazda",
      "JN", "Nissan",
      "JS", "Suzuki",
      "JT", "Toyota",
      "JY", "Yamaha",
      "KL", "Daewoo/GM Korea",
      "MH", "Hyundai",
      "KN", "Kia",
      "PT", "SsangYong",
      "6T", "Geely",
      "BE", "Beijing Hyundai",
      "BV", "BMW Brilliance",
      "DC", "Dongfeng Peugeot-Citroën",
      "E4", "Beijing Benz",
      "FM", "FAW Toyota (Sichuan)",
      "FP", "FAW Car",
      "FV", "FAW-Volkswagen",
      "GB", "Dongfeng Nissan",
      "GJ", "Dongfeng Fengshen",
      "GW", "Great Wall (Havel)",
      "GX", "BYD Auto",
      "H1", "FAW Haima",
      "HG", "Guangzhou Honda",
      "J1", "JAC",
      "JD", "Dongfeng Yueda Kia",
      "LV", "Lifan",
      "MG", "GAC Trumpchi",
      "PA", "Changan PSA (DS Automobiles)",
      "S5", "Changan Suzuki",
      "SG", "SAIC General Motors",
      "SJ", "SAIC MG",
      "SV", "SAIC Volkswagen",
      "TV", "FAW Toyota (Tianjin)",
      "VG", "GAC Toyota",
      "VH", "Dongfeng Honda",
      "VR ", "Changan Mazda",
      "VS", "Changan Ford",
      "VV", "Chery",
      "WV", "GAC Fiat",
      "ZW", "SAIC GM Wuling",
      "M0", "Mazda",
      "S0", "KIA Myanmar",
      "MT", "Toyota",
      "M0", "Ford Otosan",
      "L1", "Proton",
      "AJ ", "Jaguar",
      "AL", "Land Rover",
      "AR", "Rover",
      "AT", "Triumph",
      "B1", "Toyota",
      "CC", "Lotus Cars",
      "CF", "Aston Martin Lagonda Limited",
      "CE", "DeLorean",
      "FD", "Alexander Dennis",
      "HH", "Honda",
      "HS", "Nissan",
      "CC", "Micro Compact Car AG (SMART 1998-1999)",
      "MA", "Hyundai",
      "MB", "Škoda",
      "RU", "Audi",
      "SM", "Suzuki",
      "5Y", "Kia",
      "UU", "Dacia",
      "A0", "ÖAF",
      "F1", "Renault",
      "F2", "Renault",
      "F3", "Peugeot",
      "F4", "Talbot",
      "F5", "Iveco Unic SA",
      "F6", "Renault Trucks/Volvo",
      "F7", "Citroën",
      "F8", "Matra/Talbot/Simca",
      "F9", "Bugatti",
      "FE", "IvecoBus",
      "NK", "Toyota",
      "SS", "SEAT",
      "V9", "Tauro Sport Auto",
      "AG", "Neoplan",
      "AU", "Audi",
      "AP", "Alpina",
      "BA", "BMW",
      "BS", "BMW M",
      "BX", "BMW",
      "DB", "Mercedes-Benz",
      "DC", "DaimlerChrysler AG/Daimler AG",
      "DD", "DaimlerChrysler AG/Daimler AG",
      "MX", "DaimlerChrysler AG/Daimler AG",
      "EB", "EvoBus",
      "F0", "Ford of Europe",
      "JM", "Iveco",
      "JR", "Irmscher",
      "Irmscher", "Karl Kässbohrer Fahrzeugwerke",
      "MA", "MAN",
      "ME", "Smart",
      "MW", "Mini",
      "P0", "Porsche car",
      "P1", "Porsche SUV",
      "UA", "Quattro",
      "VG", "Volkswagen",
      "VW", "Volkswagen",
      "V1", "Volkswagen Commercial Vehicles",
      "V2", "Volkswagen Commercial Vehicles",
      "09", "Ruf Automobile",
      "0L", "Opel/Vauxhall",
      "SV", "Opel Special Vehicles",
      "LR", "DAF Trucks",
      "K1", "Saab",
      "S2", "Scania, Södertälje",
      "S3", "Saab",
      "S4", "Scania, Katrineholm",
      "TN", "Saab NEVS",
      "V1", "Volvo Cars",
      "V2", "Volvo Trucks",
      "V3", "Volvo Buses",
      "A9", "Bugatti",
      "AM", "Maserati",
      "AR", "Alfa Romeo",
      "CF", "Iveco",
      "FA", "Fiat Automobiles",
      "FF", "Ferrari",
      "GA", "IvecoBus",
      "HW", "Lamborghini",
      "LA", "Lancia",
      "1B", "Dodge",
      "1C", "Chrysler",
      "1F", "Ford",
      "1G", "General Motors",
      "G1", "Chevrolet",
      "G3", "Oldsmobile",
      "GC", "Chevrolet",
      "GM", "Pontiac",
      "HG", "Honda",
      "1J", "Jeep",
      "1L", "Lincoln",
      "1M", "Mercury",
      "1N", "Nissan",
      "VW", "Volkswagen",
      "YV", "Mazda",
      "DG", "Ontario Drive & Gear",
      "2F", "Ford",
      "2G", "General Motors",
      "G1", "Chevrolet",
      "G2", "Pontiac",
      "HG", "Honda",
      "HH", "Acura",
      "HJ", "Honda",
      "HK", "Honda",
      "HM", "Hyundai",
      "2M", "Mercury",
      "2T", "Toyota",
      "3F", "Ford",
      "3G", "General Motors",
      "HG", "Honda",
      "HM", "Honda",
      "KP", "Kia",
      "3N", "Nissan",
      "VW", "Volkswagen",
      "4F", "Mazda",
      "4J", "Mercedes-Benz",
      "4M", "Mercury",
      "S3", "Subaru",
      "S4", "Subaru",
      "S6", "Honda",
      "4T", "Toyota",
      "US", "BMW",
      "FN", "Honda",
      "J6", "Honda",
      "5L", "Lincoln",
      "5N", "Hyundai",
      "5T", "Toyota",
      "5U", "BMW",
      "5X", "Hyundai/Kia",
      "YJ", "Tesla",
      "55", "Mercedes-Benz",
      "6F", "Ford",
      "6G", "General Motors",
      "G1", "Chevrolet",
      "G2", "Pontiac",
      "6H", "Holden",
      "MM", "Mitsubishi",
      "T1", "Toyota",
      "A3", "Honda",
      "AP", "Fiat",
      "AF", "Ford",
      "AG", "General Motors",
      "AW", "Volkswagen",
      "AJ", "Toyota",
      "A1", "Renault",
      "AC", "Mercedes Benz",
      "BC", "Citroën",
      "AD", "Peugeot",
      "C3", "Honda",
      "AT", "Iveco",
      "BD", "Fiat Automóveis",
      "BG", "General Motors",
      "BW", "Volkswagen",
      "BF", "Ford",
      "3H", "Honda",
      "BR", "Toyota",
      "36", "Peugeot",
      "35", "Citroën",
      "3Y", "Renault",
      "3X", "Souza Ramos - Mitsubishi / Suzuki",
      "BH", "Hyundai Motor Company / Hyundai",
      "5P", "CAOA / Hyundai",
      "4D", "Nissan",
      "8R", "Chery",
      "88", "Jeep",
      "8M", "BMW",
      "BM", "Mercedes Benz",
      "9A", "Audi",
      "9J", "JLR Jaguar Land Rover",
      "C2", "Honda Motorcycles",
      "C6", "Yamaha",
      "CD", "Suzuki Motorcycles",
      "3W", "Fiat Professional",
      "3Z", "Iveco",
      "53", "VW Trucks / MAN",
      "BS", "Scania",
      "BV", "Volvo Trucks",
      "UJ", "Chery",
      "UK", "Lifan",
      "UW", "Kia",
      "N1", "Nissan",
      "N6", "Nissan",
      "P4", "Chrysler",
      "TM", "Toyota",
     
  };

  public static CatalogueManufacturer getDefault() {
    CatalogueManufacturer defaultMap = new CatalogueManufacturer();
    int len = ManufacturerCodes.length;
    for (int i = 0; i < len; i++) {
      String code = ManufacturerCodes[i++];
      String manufacturer = ManufacturerCodes[i];
      defaultMap.put(code, manufacturer);
    }
    return defaultMap;
  }

}

